# Common Labels
labels:
  app: "verification-service"
  group: "rainmaker"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "verification-service"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "verification_service_schema"
    image:
      repository: "verification-service-db"

# Container Configs
image:
  repository: "verification-service"
replicas: "1"
healthChecks:
  enabled: false
  livenessProbePath: "/verification-service/health"
  readinessProbePath: "/verification-service/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx256m -Xms256m"
java-args: "-Dspring.profiles.active=monitoring"
notification-sms-enabled: ""
employee-allowed-search-params: ""
citizen-allowed-search-params: ""

# Additional Container Envs
env: |
  - name: STATE_LEVEL_TENANT_ID
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-state-level-tenant-id
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_USER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user
  - name: MODULE_HOST_ADVERTISEMENT
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: adv-services
  - name: MODULE_HOST_PROPERTY
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: property-services
  - name: MODULE_HOST_TRADELICENSE
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: tl-services
  - name: MODULE_HOST_STREETVENDING
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: sv-services
  - name: MODULE_HOST_PET
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: pet-services
  - name: MODULE_HOST_EWASTE
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: ewaste-services
  - name: MODULE_HOST_COMMUNITYHALL
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: chb-services
  - name: MODULE_HOST_FIRENOC
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: firenoc-services
  - name: MODULE_HOST_BPA
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: bpa-services
  - name: MODULE_HOST_SEWERAGE
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: sw-services
  {{- if index .Values "global" "tracer-errors-provideexceptionindetails" }}
  - name: TRACER_ERRORS_PROVIDEEXCEPTIONINDETAILS
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: tracer-errors-provideexceptionindetails
  {{- end }}
  - name: KAFKA_TOPIC_AUDIT
    value: "enc-user-audit-data" 
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
    value: org.springframework.kafka.support.serializer.JsonSerializer
  - name: JAVA_ENABLE_DEBUG
    value: "true"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: NOTIFICATION_URL
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-services-fqdn-name      
  {{- if index .Values "employee-allowed-search-params" }}
  - name: EMPLOYEE_ALLOWED_SEARCH_PARAMS
    value: {{ index .Values "employee-allowed-search-params" | quote }}
  {{- end }}
  {{- if index .Values "citizen-allowed-search-params" }}
  - name: CITIZEN_ALLOWED_SEARCH_PARAMS
    value: {{ index .Values "citizen-allowed-search-params" | quote }}
  {{- end }}
  - name: EGOV_UI_APP_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-services-fqdn-name       
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
